name: Build ERPNext Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # This step reads the file and saves the base64 string to a variable
      - name: Encode apps.json to Base64
        id: encode_json
        run: |
          ENCODED=$(base64 -w 0 apps.json)
          echo "apps_base64=$ENCODED" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/erpnext-custom:latest
          # We pull the value from the 'encode_json' step above
          build-args: |
            APPS_JSON_BASE64=${{ steps.encode_json.outputs.apps_base64 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
