name: Build ERPNext Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Secrets Presence
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then echo "❌ DOCKERHUB_USERNAME is MISSING"; exit 1; fi
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then echo "❌ DOCKERHUB_TOKEN is MISSING"; exit 1; fi
          echo "✅ All secrets are present."

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/erpnext-custom:latest
